# Generated by Django 6.0.6 on 2026-07-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptom_summary',
            field=models.TextField(blank=True),
        ),
    ]
